#!/bin/bash

echo "========================================="
echo "   🏛️ AASA SAGRADO - AMBIENTE PRONTO"
echo "========================================="
echo ""
echo "📌 TERMINAL 1 - BACKEND"
echo "   Comando: npm run dev"
echo "   Pasta: backend/"
echo ""
echo "📌 TERMINAL 2 - DESENVOLVIMENTO"
echo "   Comandos disponíveis:"
echo "   - git status      : Ver alterações"
echo "   - git add .       : Adicionar arquivos"
echo "   - git commit -m   : Commitar"
echo "   - git push        : Enviar para GitHub"
echo "   - git pull        : Baixar atualizações"
echo ""
echo "========================================="
echo "   ✅ AMBIENTE PRONTO PARA USAR!"
echo "========================================="
